- name: MySQL setup
  hosts: all
  become: yes
  tasks:
    - name: Install MySQL
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Enable MySQL
      ansible.builtin.systemd_service:
        name: mysqld
        state: started
        enabled: true

    - name: Change MySQL Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1