- name: Disable nodejs module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs module
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: latest

- name: Create an application user
  ansible.builtin.user:
    name: expense

- name: Import pre-req tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: npm dependencies install
  community.general.npm:
    path: /app
    state: latest

- name: Copy Backend service file
  ansible.builtin.template:
    src: templates/backend.service
    dest: /etc/systemd/system/backend.service

- name: Install Python Mysql client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Install requests python package
  pip:
    name: requests
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Load schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.pappik.online

- name: restart backend
  ansible.builtin.systemd_service:
    name: backend
    daemon_reload: true
    state: started
    enabled: true