- name: Disable nodejs module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs module
  ansible.builtin.shell: dnf module enable nodejs:20 -y

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: latest

- name: Create an application user
  ansible.builtin.user:
    name: expense

- name: Import pre-req tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: npm dependencies install
  community.general.npm:
    path: /app
    state: latest

- name: Copy config file to location
  ansible.builtin.copy:
    src: files/backend.service
    dest: /etc/systemd/system/backend.service

- name: restart backend
  ansible.builtin.systemd_service:
    name: backend
    daemon_reload: true
    state: started
    enabled: true

- name: Install Mysql client
  ansible.builtin.dnf:
    name: mysql
    state: latest
- name: Enable nodejs module
  ansible.builtin.shell: mysql -h mysql-dev.pappik.online -uroot -pExpenseApp@1 < /app/schema/backend.sql


