- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest
- name: Enable Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true

- name: Import pre-req tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: Copy config file to location
  ansible.builtin.template:
    src: templates/expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: restart Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted